### ISSUE TITLE
I like the preparation for the war :)

### ISSUE THREAD

**Issue by ArkaprabhaChakraborty** [Eshanatnight/College#1]
Let's hope we win it !!!!!!!!! :)

**Comment by Eshanatnight** [comment]
Clean Up the ctrl, c and v keys will need it :")

**Comment by ArkaprabhaChakraborty** [comment]
Thanks for the carry-save adder .... didn't even know that EXISTS.... :)

**Comment by Eshanatnight** [comment]
Life is full of surprises :")
